"""changed schema for leaves

Revision ID: 2d3e60be81e5
Revises: bc8554603922
Create Date: 2020-02-23 22:53:48.479214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d3e60be81e5'
down_revision = 'bc8554603922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_username', sa.String(length=64), nullable=True),
    sa.Column('faculty_username', sa.String(length=64), nullable=True),
    sa.Column('from_date', sa.DateTime(), nullable=True),
    sa.Column('to_date', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('type_of_leave', sa.String(length=64), nullable=True),
    sa.Column('leave_status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaves_faculty_username'), 'leaves', ['faculty_username'], unique=True)
    op.create_index(op.f('ix_leaves_from_date'), 'leaves', ['from_date'], unique=False)
    op.create_index(op.f('ix_leaves_leave_status'), 'leaves', ['leave_status'], unique=False)
    op.create_index(op.f('ix_leaves_reason'), 'leaves', ['reason'], unique=False)
    op.create_index(op.f('ix_leaves_student_username'), 'leaves', ['student_username'], unique=True)
    op.create_index(op.f('ix_leaves_to_date'), 'leaves', ['to_date'], unique=False)
    op.create_index(op.f('ix_leaves_type_of_leave'), 'leaves', ['type_of_leave'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaves_type_of_leave'), table_name='leaves')
    op.drop_index(op.f('ix_leaves_to_date'), table_name='leaves')
    op.drop_index(op.f('ix_leaves_student_username'), table_name='leaves')
    op.drop_index(op.f('ix_leaves_reason'), table_name='leaves')
    op.drop_index(op.f('ix_leaves_leave_status'), table_name='leaves')
    op.drop_index(op.f('ix_leaves_from_date'), table_name='leaves')
    op.drop_index(op.f('ix_leaves_faculty_username'), table_name='leaves')
    op.drop_table('leaves')
    # ### end Alembic commands ###
