"""relationship table

Revision ID: 9c43dc4318ea
Revises: a3260db21437
Create Date: 2020-03-13 19:02:33.235193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c43dc4318ea'
down_revision = 'a3260db21437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisor',
    sa.Column('student_username', sa.String(length=64), nullable=False),
    sa.Column('faculty_username', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('student_username')
    )
    op.create_index(op.f('ix_advisor_faculty_username'), 'advisor', ['faculty_username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advisor_faculty_username'), table_name='advisor')
    op.drop_table('advisor')
    # ### end Alembic commands ###
