"""empty message

Revision ID: a3260db21437
Revises: 2d3e60be81e5
Create Date: 2020-02-24 01:04:53.820118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3260db21437'
down_revision = '2d3e60be81e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leaves_faculty_username', table_name='leaves')
    op.create_index(op.f('ix_leaves_faculty_username'), 'leaves', ['faculty_username'], unique=False)
    op.drop_index('ix_leaves_student_username', table_name='leaves')
    op.create_index(op.f('ix_leaves_student_username'), 'leaves', ['student_username'], unique=False)
    op.drop_index('ix_leaves_type_of_leave', table_name='leaves')
    op.create_index(op.f('ix_leaves_type_of_leave'), 'leaves', ['type_of_leave'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaves_type_of_leave'), table_name='leaves')
    op.create_index('ix_leaves_type_of_leave', 'leaves', ['type_of_leave'], unique=1)
    op.drop_index(op.f('ix_leaves_student_username'), table_name='leaves')
    op.create_index('ix_leaves_student_username', 'leaves', ['student_username'], unique=1)
    op.drop_index(op.f('ix_leaves_faculty_username'), table_name='leaves')
    op.create_index('ix_leaves_faculty_username', 'leaves', ['faculty_username'], unique=1)
    # ### end Alembic commands ###
