"""users table

Revision ID: bc8554603922
Revises: 
Create Date: 2020-02-23 19:30:52.764172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc8554603922'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculty_user_email'), 'faculty_user', ['email'], unique=True)
    op.create_index(op.f('ix_faculty_user_username'), 'faculty_user', ['username'], unique=True)
    op.create_table('student_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_user_email'), 'student_user', ['email'], unique=True)
    op.create_index(op.f('ix_student_user_username'), 'student_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_user_username'), table_name='student_user')
    op.drop_index(op.f('ix_student_user_email'), table_name='student_user')
    op.drop_table('student_user')
    op.drop_index(op.f('ix_faculty_user_username'), table_name='faculty_user')
    op.drop_index(op.f('ix_faculty_user_email'), table_name='faculty_user')
    op.drop_table('faculty_user')
    # ### end Alembic commands ###
